version: "3"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrance_log
    networks:
      mysql_network:
        ipv4_address: 172.20.0.2
    volumes:
       - data-volume:/var/lib/mysql
 
volumes:
 data-volume:
networks:
  mysql_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.2/16